spring.main.allow-bean-definition-overriding=true
server.error.include-stacktrace=always
spring.thymeleaf.cache=false
# for testconfig
logging.level.ro.editii=DEBUG
logging.level.ro.editii.scriptorium.tei.TeifileParser=INFO
logging.level.editii=DEBUG