package ro.editii.scriptorium.vector;

import com.google.common.collect.Lists;
import io.milvus.common.clientenum.ConsistencyLevelEnum;
import io.milvus.grpc.*;
import io.milvus.param.IndexType;
import io.milvus.param.MetricType;
import io.milvus.param.R;
import io.milvus.param.collection.*;
import io.milvus.param.control.ManualCompactParam;
import io.milvus.param.dml.InsertParam;
import io.milvus.param.dml.SearchParam;
import io.milvus.param.dml.UpsertParam;
import io.milvus.param.highlevel.dml.QuerySimpleParam;
import io.milvus.param.highlevel.dml.SearchSimpleParam;
import io.milvus.param.highlevel.dml.response.SearchResponse;
import io.milvus.param.index.CreateIndexParam;
import io.milvus.response.QueryResultsWrapper;
import io.milvus.response.SearchResultsWrapper;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;


@RequiredArgsConstructor @Log4j2
public class MilvusCollection {

    // how many buckets should be the vector search space split into
    public static final int DEFAULT_NLIST = 256;
    // how many buckets to try out at search-time of total nlist
    public static final int DEFAULT_NPROBE = 10;
    public static final int DEFAULT_TOPK = 10;

    public static final String FIELD_SHA_256 = "sha256";
    public static final String FIELD_EMBEDDING = "embedding";
    public static final String FIELD_URL = "url";

    public static  final short DIM_384 = 384;
    public static  final short DIM_768 = 768;
    public static  final short DIM_1024 = 1024;
    public static  final short DIM_2560 = 2560;

    public static final String DESCRIPTION_SHA_256 = "Primary key: lowercase SHA-256 hex digest of the source paragraph text. Used to deduplicate unchanged text across imports.";
    public static final String DESCRIPTION_URL = "Canonical Textbase API URL identifying the source paragraph. Use it to retrieve the text and its document context.";
    public static final String DESCRIPTION_EMBEDDING = "Dense semantic vector generated by the encoder documented in this collection description. Query vectors must use that same encoder and dimension.";

    final MilvusService milvusService;
    final String name;
    private Integer vectorDimension;

    public String getName() {
        return this.name;
    }

    public void load() {
        this.milvusService.loadCollection(name);
    }

    public void createIndexIvfFlat() {
        this.milvusService.milvus.createIndex(CreateIndexParam.newBuilder()
            .withCollectionName(this.name)
            .withFieldName(FIELD_EMBEDDING)
            .withIndexName("idx_" + this.name)
            .withIndexType(IndexType.IVF_FLAT)
            .withMetricType(MetricType.L2)
            .withExtraParam(nListParam(DEFAULT_NLIST))
            .build());
    }

    public void createIndexIvfSq8() {
        this.milvusService.milvus.createIndex(CreateIndexParam.newBuilder()
                .withCollectionName(this.name)
                .withFieldName(FIELD_EMBEDDING)
                .withIndexName("idx_" + this.name)
                .withIndexType(IndexType.IVF_SQ8)
                .withMetricType(MetricType.L2)
                .withExtraParam(nListParam(DEFAULT_NLIST))
                .build());
    }

    String nListParam(int nList) {
        assert nList > 0;
        return String.format("{\"nlist\": \"%d\"}", nList);
    }

    public void create(int vectorDimension) {
        this.create(vectorDimension, "embeddings storage create on " + new Date());
    }

    /**
     * @param description should identify the encoder that produced (or will
     *                     produce) this collection's vectors - where it runs
     *                     and its name/characteristics - since a collection
     *                     is only ever compatible with vectors from the one
     *                     encoder it was created for (see
     *                     MilvusTextSearchService.validateModelCollectionCompatible).
     *                     Callers that just need a generic collection
     *                     (most existing tests) can use the single-arg
     *                     create(int) overload instead.
     */
    public void create(int vectorDimension, String description) {
        this.vectorDimension = vectorDimension;
        this.milvusService.milvus.createCollection(CreateCollectionParam.newBuilder()
                .withCollectionName(this.name)
                .withConsistencyLevel(ConsistencyLevelEnum.EVENTUALLY)
                .withDescription(description)
                .withFieldTypes(List.of(
                    FieldType.newBuilder()
                        .withPrimaryKey(true)
                        .withName(FIELD_SHA_256)
                        .withDescription(DESCRIPTION_SHA_256)
                        .withDataType(DataType.VarChar)
                        .withMaxLength(512)
                        .build(),
                    FieldType.newBuilder()
                        .withName(FIELD_URL)
                        .withDescription(DESCRIPTION_URL)
                        .withDataType(DataType.VarChar)
                        .withMaxLength(512)
                        .build(),
                    FieldType.newBuilder()
                        .withName(FIELD_EMBEDDING)
                        .withDescription(DESCRIPTION_EMBEDDING)
                        .withDataType(DataType.FloatVector)
                        .withDimension(vectorDimension)
                        .build()
                ))
                .build());
    }

    public boolean exists() {
        return this.milvusService.has(this.name);
    }

    public void release() {
        this.milvusService.milvus.releaseCollection(
                ReleaseCollectionParam.newBuilder()
                        .withCollectionName(this.name)
                        .build());
    }

    public void drop() {
        this.milvusService.dropCollection(this.name);
    }

    public SearchResultsWrapper search(float[] vector, int topK) {
        return this.search(new float[][] {vector}, topK );
    }

    public SearchResultsWrapper search(float[][] vectors, int topK) {
        final var asList = VectorUtils.arr2List(vectors);
        return this.search(asList, topK);
    }

    public SearchResultsWrapper search(List<List<Float>> vectors) {
        return this.search(vectors,  DEFAULT_TOPK);
    }

    public SearchResultsWrapper search(List<List<Float>> vectors, int topK) {
        return this.search(vectors, DEFAULT_NPROBE, topK);
    }

    public SearchResultsWrapper search(float[] vector) {
        return this.search(vector, DEFAULT_NPROBE, DEFAULT_TOPK);
    }

    public SearchResultsWrapper search(float[] vector, int nProbe, int topK) {
        return this.search(new float[][] { vector}, nProbe, topK);
    }

    public SearchResultsWrapper search(float[][] vectors) {
        return this.search(vectors, DEFAULT_NPROBE, DEFAULT_TOPK);
    }

    public SearchResultsWrapper search(float[][] vectors, int nProbe, int topK) {
        return this.search(VectorUtils.arr2List(vectors), nProbe, topK);
    }

    public SearchResultsWrapper search(List<List<Float>> vectors, int nProbe, int topK) {

        final SearchParam params = searchParamIvfL2Eventually(vectors, topK, nProbe);
        final R<SearchResults> respSearch = this.milvusService.milvus.search(params);

        final SearchResultsWrapper wrapperSearch = new SearchResultsWrapper(respSearch.getData().getResults());
        return wrapperSearch;
    }

    private SearchParam searchParamIvfL2Strong(List<List<Float>> vectors, int topK, int nProbe) {
        final String SEARCH_PARAM = String.format("{\"nprobe\": %d, \"offset\":0}", nProbe);
        final List<String> search_output_fields = Arrays.asList(FIELD_SHA_256);
        return SearchParam.newBuilder()
                .withCollectionName(this.name)
                .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
                .withMetricType(MetricType.L2)
                .withOutFields(search_output_fields)
                .withTopK(topK)
                .withVectors(vectors)
                .withVectorFieldName(FIELD_EMBEDDING)
                .withParams(SEARCH_PARAM)
                .build();
    }

    private SearchParam searchParamIvfL2Eventually(List<List<Float>> vectors, int topK, int nProbe) {
        final String SEARCH_PARAM = String.format("{\"nprobe\": %d, \"offset\":0}", nProbe);
        final List<String> search_output_fields = Arrays.asList(FIELD_SHA_256, FIELD_URL);
        return SearchParam.newBuilder()
                .withCollectionName(this.name)
                .withConsistencyLevel(ConsistencyLevelEnum.EVENTUALLY)
                .withMetricType(MetricType.L2)
                .withOutFields(search_output_fields)
                .withTopK(topK)
                .withVectors(vectors)
                .withVectorFieldName(FIELD_EMBEDDING)
                .withParams(SEARCH_PARAM)
                .build();
    }


    void search2(float[][] vectors) {
        this.search2(VectorUtils.arr2List(vectors));
    }

    /**
     * https://milvus.io/api-reference/java/v2.3.x/High-level%20API/search().md
     */
    void search2(List<List<Float>> vectors) {

        SearchSimpleParam param = SearchSimpleParam.newBuilder()
                .withCollectionName(this.name)
                .withVectors(vectors)
                .withOutputFields(Lists.newArrayList("*"))
                .withFilter("")
                .withLimit(100L)
                .withOffset(0L)
                .build();

        R<SearchResponse> response = this.milvusService.milvus.search(param);
        if (response.getStatus() != R.Status.Success.getCode()) {
            System.out.println(response.getMessage());
        }

        for (QueryResultsWrapper.RowRecord rowRecord : response.getData().getRowRecords()) {
            System.out.println(rowRecord);
        }
    }

    public R<GetCollectionStatisticsResponse> getStatistics() {
        return this.milvusService.milvus.getCollectionStatistics(GetCollectionStatisticsParam.newBuilder()
                .withCollectionName(this.name)
                .build());
    }

    /** The description this collection was created with (see create(dim, description)) - null if it doesn't exist. */
    public String getDescription() {
        final R<DescribeCollectionResponse> resp = this.milvusService.milvus.describeCollection(
                DescribeCollectionParam.newBuilder()
                        .withCollectionName(this.name)
                        .build());
        return resp.getData().getSchema().getDescription();
    }

    public int getVectorDimension() {
        final R<DescribeCollectionResponse> resp = this.milvusService.milvus.describeCollection(
                DescribeCollectionParam.newBuilder().withCollectionName(this.name).build());
        return resp.getData().getSchema().getFieldsList().stream()
                .filter(field -> FIELD_EMBEDDING.equals(field.getName()))
                .flatMap(field -> field.getTypeParamsList().stream())
                .filter(param -> "dim".equals(param.getKey()))
                .mapToInt(param -> Integer.parseInt(param.getValue()))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("Collection '" + this.name + "' has no embedding dimension"));
    }

    /** Field comments persisted in the actual Milvus schema. */
    public Map<String, String> getFieldDescriptions() {
        final R<DescribeCollectionResponse> resp = this.milvusService.milvus.describeCollection(
                DescribeCollectionParam.newBuilder().withCollectionName(this.name).build());
        return resp.getData().getSchema().getFieldsList().stream()
                .collect(Collectors.toMap(FieldSchema::getName, FieldSchema::getDescription));
    }

    public R<ShowCollectionsResponse> getInfo() {
        R<ShowCollectionsResponse> resp = this.milvusService.milvus.showCollections(
                ShowCollectionsParam.newBuilder()
                        .addCollectionName(name)
                        .build()
        );
        return resp;
    }

    public R<FlushResponse> flush() {
        final var resp = this.milvusService.milvus.flush(FlushParam.newBuilder()
            .withCollectionNames(List.of(this.name))
            .build());
        return resp;
    }

    public R<ManualCompactionResponse> compact() {
        R<ManualCompactionResponse> response = this.milvusService.milvus.manualCompact(
                ManualCompactParam.newBuilder()
                        .withCollectionName(this.name)
                        .build()
        );
        return response;
    }

    public R<MutationResult> insert(Content[] content) {
        @NonNull List<InsertParam.Field> fields = prepareInsertParams(content);

        final var mutationResultR = this.milvusService.milvus.insert(InsertParam.newBuilder()
                .withCollectionName(this.name)
                .withFields(fields)
                .build());

        return mutationResultR;
    }

    public R<MutationResult> upsert(Content[] content) {
        @NonNull List<UpsertParam.Field> fields = prepareUpsertParams(content);

        final UpsertParam param = UpsertParam.newBuilder()
                .withCollectionName(this.name)
                .withFields(fields)
                .build();

        final var mutationResultR = this.milvusService.milvus.upsert(param);

        return mutationResultR;
    }

    private List<UpsertParam.Field> prepareUpsertParams(Content[] content) {
        final IdsUrlsAndVectors idsUrlsAndVectors = this.prepFields(content);

        final List<UpsertParam.Field> fields = new ArrayList<>();
        fields.add(UpsertParam.Field.builder()
                .name(MilvusCollection.FIELD_SHA_256)
                .values(idsUrlsAndVectors.ids)
                .build());
        fields.add(UpsertParam.Field.builder()
                .name(MilvusCollection.FIELD_URL)
                .values(idsUrlsAndVectors.urls)
                .build());
        fields.add(UpsertParam.Field.builder()
                .name(MilvusCollection.FIELD_EMBEDDING)
                .values(idsUrlsAndVectors.vectors)
                .build());

        return  fields;
    }

    private IdsUrlsAndVectors prepFields(Content[] content) {
        assert content != null;

        final var ids = Arrays.stream(content).map(it -> it.sha256).toList();
        final var urls = Arrays.stream(content).map(it -> it.url).toList();
        final List<List<Float>> vectorsAsListofLists = Arrays.stream(content).map(it -> {
            final var vect = it.embedding;
            assert vect.length == this.vectorDimension;
            final var resp = VectorUtils.arr2List(vect);
            return resp;
        }).toList();

        return new IdsUrlsAndVectors(ids, urls, vectorsAsListofLists);
    }

    private List<InsertParam.Field> prepareInsertParams(Content[] content) {

        final IdsUrlsAndVectors idsUrlsAndVectors = this.prepFields(content);

        final List<InsertParam.Field> fields = new ArrayList<>();
        fields.add(InsertParam.Field.builder()
                .name(MilvusCollection.FIELD_SHA_256)
                .values(idsUrlsAndVectors.ids)
                .build());
        fields.add(InsertParam.Field.builder()
                .name(MilvusCollection.FIELD_URL)
                .values(idsUrlsAndVectors.urls)
                .build());
        fields.add(InsertParam.Field.builder()
                .name(MilvusCollection.FIELD_EMBEDDING)
                .values(idsUrlsAndVectors.vectors)
                .build());

        return  fields;
    }

    public Content findBySha256(String sha256) {
        final var resp = this.milvusService.milvus.query(QuerySimpleParam.newBuilder()
                .withCollectionName(this.name)
                .withFilter(String.format("sha256 == '%s'", sha256))
                .withOutputFields(List.of(FIELD_SHA_256, FIELD_URL, FIELD_EMBEDDING))
                .build());
        final var recs = resp.getData().getRowRecords();
        final var list = recs.stream().map(it ->
             Content.builder()
                    .sha256((String) it.get(FIELD_SHA_256))
                    .url((String) it.get(FIELD_URL))
                    .embedding((float[]) it.get(FIELD_EMBEDDING))
                    .build())
                .toList();
        if (list.size() > 1) {
            // should not have two or more elements since sha256 is primary key
            log.warn(String.format("findBySha256() returns %d elems for [%s]", list.size(), sha256));
        }
        if (!list.isEmpty())
            return list.iterator().next();
        else
            return null;
    }

    /**
     * this is basically a split up List<Content>, just as milvus likes it
     */
    record IdsUrlsAndVectors(List<String> ids, List<String> urls, List<List<Float>> vectors) {}

    @Override
    public String toString() {
        return "MilvusCollection{" +
                "milvusService=" + milvusService.toString() +
                ", name='" + name + '\'' +
                ", vectorDimension=" + vectorDimension +
                '}';
    }
}
